### PR TITLE
Add ZCD library

### PR DESCRIPTION
**Pull request by MCUdude**

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Ooooh, spiffy! One problem - on the initial silicon, you can't swap the ZCD output pins individually. ZCD0's swap bit controls all three, and the other two bits do nothing....

**Comment by MCUdude** [comment]
> One problem - on the initial silicon, you can't swap the ZCD output pins individually. ZCD0's swap bit controls all three, and the other two bits do nothing...

Damn it! Do you know if this has been fixed and a new silicon revision is available?
I guess we'll have to do a workaround. How about 
```c++
zcd.pinswap = out::swap_all;
```
?

**Comment by MCUdude** [comment]
BTW the pinout pics should be updated with ZCD. I'll fix it when this PR is merged. One of us should open a separate issue regarding this though.

**Comment by MCUdude** [comment]
> One problem - on the initial silicon, you can't swap the ZCD output pins individually. ZCD0's swap bit controls all three, and the other two bits do nothing...

Do you know if this is true for _all_ AVR DA and DB's? I'll have to document this in the readme, but I'd like to point out what chips are affected and which are not.

**Comment by SpenceKonde** [comment]
It does effect all AVR32DA and AVR64DA parts (present in all released revisions). I do not think it effects DB128 parts. And you have DA128 silicon on hand to check (I would wager that it does

**Comment by MCUdude** [comment]
out::swap_all added! I think this library is pretty much finished. At least it does what it's supposed to do!

**Comment by SpenceKonde** [comment]
Thanks!

**Pull request merged**
