### PR TITLE
Fix Wire library regression plus a little optimization

### PR DESCRIPTION
**Pull request by MX682X**
also some adjustments in the documentation

### CODE REVIEW

**Comment by MX682X** [comment]
Since you are still working out the details on the core (I guess), there is one more thing I stumbled upon by chance: https://github.com/SpenceKonde/DxCore/blob/94ff095347ede99cabb72864f3250b1f55cc571d/megaavr/cores/dxcore/WInterrupts.c#L153
You are always pushing RAMPZ, even though only a handful of parts even have this register. I suggest to use the built-in gcc define __AVR_HAVE_RAMPZ__ to save some bytes on the smaller parts by checking if it is defined

**Comment by SpenceKonde** [comment]
Thanks, as you can see i was thinking only of the AVR128Dx parts when writing that library.

**Comment by SpenceKonde** [comment]
fixes #396 #401 #393

**Comment by SpenceKonde** [comment]
Yo we got a little problem here. There are currently differences from megaTinyCore version. I don't know which ones are the correct ones in all cases:
Wire.cpp
```c++
 *@return     size_t
 *@retval     amount of bytes copied
 */
size_t TwoWire::write(const uint8_t *data, size_t quantity) {
  twi_buffer_index_t i = 0;
  for (; i < quantity; i++) {
    if (TwoWire::write(*(data++)) == 0)
      break;   // break if buffer full
  }

  return i;
}
```
vs
```
 *@return     uint8_t
 *@retval     amount of bytes copied
 */
size_t TwoWire::write(const uint8_t *data, size_t quantity) {
  twi_buffer_index_t i = 0;
  twi_buffer_index_t qty = (quantity >= BUFFER_LENGTH) ? BUFFER_LENGTH : quantity; //Don't overfill the buffer.
  for (; i < qty; i++) {
    if (write(*(data + i)) == 0) break;   // break if buffer full
  }

  return i;
}
```
Not sure which direction this should be merged. 


twi.c
```
/*@retval     error code, if enabled. Not 0 means something went wrong
 */
```
vs
```
/@retval     amount of bytes that were written. If 0, no write took place, either due
 *            to an error or because of an empty txBuffer
 ```

Which is correct? this sounds really familiar.

```__asm__ __volatile__("\n\t": "=&y" (_data) : "0" (_data));  // force _data into Y and instruct to not change Y
```
vs
```_fastPtr_y(_data,_data);  // force _data into Y and instruct to not change Y
```
I'm planning to add dirty_tricks.h to DxCore, and was thinking to make Wire more portable by putting 
```
#ifndef _fastPtr_y 
(definition copied from dirty_tricks.h)
#endif             
```
Does that sound reasonable?

I'm guessing we want the DxC version of this one, and assume it's what fixed the bug?
```
    _data->_bools._toggleStreamFn = 0x00;
```
vs 
```
    _data->_bools._toggleStreamFn = 0x01
;
```

**Comment by MX682X** [comment]
about write (buf, length) - The changes that are part of this PR make the array write about 22 bytes shorter. Before that, there was an icall to write (byte). And as we check for bufferoverflow in the write(byte), there was no need for a second check.

the return value documentation was not corrected since the publishing, so it was still about the incorrect implementation. So I decided to fix it while going through the code. The Wire.cpp file is documented correctly.

and _toggleStreamFn = 0 is the fix, as explained in the discussion

**Pull request merged**
