### PR TITLE
Fixing the Stack problem

### PR DESCRIPTION
**Pull request by MX682X**
+ some more optimizations to get size down to 466

at this point, If i were mad enough, It could be probably possible to make the receive double-buffered allowing to store incoming data in two buffers and switch between them when while programming the flash...

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Thanks!

IMO, the real way to get double buffering on Dx is totally different:
Dispense with single buffering. I don't even know if that buffer trick you briefly described does anything. I don't think it does. 

There is one reason and one reason only that the stupid buffering was ever done: Because we had to erase the page. That takes time - too long to do while in the middle of a serial receive (Dx does not have any sort of rww. , and immediately following the memory type designation (the point at which we discover that we need to erase a page), we have 512 bytes coming straight at us with not a moment pause. If the page had been erased, we could just put every high byte into r1 and every low byte into r0, incrementing the byte count with each one, then execute SPM Z and increment Z with adiw (we don't do SPM Z+ on 128k parts, even though we wish we could, because that breaks a write that fills the flash to within 512b of halfway). 

In the more general case, it seems unlikely to be able to deal with this in 512b. But of course the more general case already doesn't work because Optiboot trimmed out just about every command, and responds to requests for information by spraying back 0's and any command other than enter programming mode, exit programming mode, read/write, the extended address command, and normal set address, it responds to by smiling and nodding and doing nothing. It only works because avrdude only needs the commands it has, and doesn't care what nonsense values you send back for board parameters.

Now - you can force avrdude to send a chip erase command, by copying the chip erase command from other devices  in the conf and telling it to erase the chip, and then have the bootloader notice and erase the flash and report success, instead of just reporting success. There are two algorithms, minimum time or minimum code
Minimum time is FLPER, erase 0x200, FLMPER2, erase 0x400, FLMPER4 erase 0x800, FLPMPER8 0x1000, FLMPER16 0x2000, FLMPER32 0x4000, 0x8000, 0xC000, 0x10000, 0x14000, 0x18000, 0x1C000 - 12 writes and 120ms. If you skip going to 32 page erases, it's 19 writes 190ms. Still easily fine. Skip 16-page blocks: 34 writes 340ms. Skip 8-page blocks: 65 writes 650ms. But here's where our luck runs out because within 128 or 255 writes, we're at 1.28 or 2.55 seconds respectively, and I think avrdude times out after a second (though it may be possible to force AVRdude to wait longer - but 2.55 seconds is starting to be slow enough to notice. 650ms would not make anyone bat an eye though - and the uploads would now be going at the speed of the wire once the flash was erased! *even if the speed of the wire was increased to 230400* (we have a 2 byte buffer effectively, as rxdata is doublebuffered by hardware, plus you should get a free almost a third byte from the input shift register), that's 43.x us per byte, and every second one, you halt the CPU for 70 us. But you don't overflow the buffer, and you have 64 clocks during which you're not halted, approximately. in which to adiw r30, 2, then getch() twice putting the results into r0..1, and execute the SPM instruction. 230400 may not actually quite work, On the other hand, IIRC via UPDI the writes are faster than advertised, and the same is likely true for self programming.

**Comment by SpenceKonde** [comment]
WTF. Why can't I build optiboot anymore? 

The makefiles are binary identical to the one that used to work, but now make says no rule to build target for all targets. There are rules to make all the fucking targets! How could changing the .c file have made make generate no rule to build target errors?!

**Comment by SpenceKonde** [comment]
I have no idea how to debug this. Normally, I debug things i don't understand by getting a diff where one works and one doesn't, but here, when I go back to the "known working" configuration with the old optiboot_d.c it's still broken. 

This is MADNESS. I fucking hate make "Something is wrong with your make file. Here's an error that tells you precisekly NOTHING

Why does it not work? What has changed? How can there not be a fucking rule to make? I'm bloody staring at the rule now.

**Comment by MX682X** [comment]
Quick lookup into my search engine suggests to remove the previously compiled binaries, because make might think that it doesn't have to build anything. Might explain why it worked beforehand.
If this won't work, I'll try to recreate the build envoirement (tried to avoid this hassle) and figure something out.

Am 24. Oktober 2023 20:17:17 MESZ schrieb "Spence Konde (aka Dr. Azzy)" ***@***.***>:

**Comment by SpenceKonde** [comment]
No it's not leftover binaries.

WTF is wrong with the Makefile. Obviously, there was never a working makefile in the repo, which happens fairly easily since makefiles have an incredibly fiddly syntax (including 

If it would be useful, I can pack up my whole optiboot_dx portable build environment (a windows folder tree consisting of an arduino 1.0.6 portable install with everything removed except the build utils, the new toolchain put in place of the old one, and the optiboot directories added to hardware/arduino/bootloaders It has no outside dependencies, and will work as long as you don;t have some other avr-gcc in your PATH; this is what I use to build with (and it gets carried between computers in this form)

**Comment by MX682X** [comment]
I've set up the build envoirment now.
But I've copied the make from arduino to your avr-gcc directory and adjusted the paths for gcc and avrdude (for what ever it is needed) and I was able to compile it with no problems by running build_all_dx.
I've also added some multi-threading compatibility in the .bat file to speed up the whole thing (Haven't figured out how to log the binary sizes.
I can add those changes to the PR if you want (there is a "typo" that errors out on parts < 64k,, but this can be fixed by copy-pasting a define)

**Comment by SpenceKonde** [comment]
https://drazzy.com/bin/optiboot_x_dx_build.tar.xz
Compressed using xzip/lzma2 - 7zip opens them and it blows bzip2 out of the water for the types of files we work with. 
It compresses the 240mb toolchain packages down to 12.x mb instead of like 45mb for stupid bzip2. 

Remember, I ain't no freeloading scrub! I *pay* for my bandwidth. Not very much, but in theory someone with a download script could put me in the poor house (the fact that the beneficiary would be the bald monopolist billionare who is unfair  and aspiring probably helps to discourage such harassment) 

That wasn't too bad. Compressed from 370mb to 21 mb - it would come to not less than 53 but likely below 73 with bz2, a (Bzip2 of toolchain is 45.x, zx of toolchain 12.x). This file contains the toolchain plus some additional crap (the build tools which are the whole point) that doesn't compress nearly as well, so it's size is 12.x MB + XZip(extra crap) = 21, ergo XZip(extra crap) = 8.x Mb If we assume that BZip2 is no better at compressing than LZMA2 (I suspect exceptions could be contrived, but they would be contrived, and the difference would be small), then the predicted bzip2 size is at least BZip2(total, min) = BZip2(toolchain) + XZip(extra crap) = 53, since we stipulated that BZip2(extra crap) >= XZip(extra crap). If we assume that bzip is as bad at all things compared to xzip to an equal degree, that would mean BZip2(extra crap) = XZip(extra crap) * BZip2(toolchain)/XZip(toolchain) . That ratio is around 3.5. This is very cruel to BZip2 and I think  it is the ceiling on plausible badness here, so BZip2(max) = 45 + 28 = 73. So yeah, the bzip2 size would hve been 53-73mb instead of 21. 


Gaaah! You beat me! 

And yeah we're talking about dx. What I don't get is my tabs are identical in the two files (optiboot_x and optiboot_dx) but it doesn't build for me. Multithreading to the bats o_o I thought that was deep magic. Didn;t even know it could be done! 

Every time I work with makefiles, I feel like something is sneaking around behind my back undoing changes, modifying files slightly, etc.

**Comment by SpenceKonde** [comment]
To be clear, yeah, I'll take the multithreaded bats. Make sure you commit any files that got changes. 

500b... 500b with eeprom and chiperase? I mean, before we had 510, no EEPROM and no chip erase, so this looks like quite an improvement.

**Comment by MX682X** [comment]
ok, so in order to check if my chip erase works, I need to make avr-dude send a chiperase with -e.
However, I have no idea how to change the config file, or rather how avrdude interprets the chip_erase = <instruction>. Right now I expect a 
#define STK_CHIP_ERASE      0x52  // 'R'
but it isn't transmitted. (I have seen a second enter/leave programming mode though)
can you help me with this @SpenceKonde or maybe @WestfW ?

**Comment by SpenceKonde** [comment]
This is what all the classics do, though that second nybble doesn't look like a 2 to me. 
```
    chip_erase       = "1 0 1 0  1 1 0 0    1 0 0 0  0 0 0 0",
                       "x x x x  x x x x    x x x x  x x x x";
```

**Comment by SpenceKonde** [comment]
Aaaha! Yeah, it looks like it may it send it as an STK Universal command, which has a fixed payload of 4 bytes. 

This is what the command looks like:
avrdude: send: V [56] . [ac] . [80] . [00] . [00]   [20]

**Comment by MX682X** [comment]
alright... chip-erase works now and completes in about 130ms for the 128k, half of it for the first 32k if we can trust the datasheet about the page erase time not depending on the page count.
I've tried to "remember" the chip erase, but turns out we get a WDR reset because avrdude always sends a LEAVE_PROGMODE after the chip erase...
So now, after reset, I check the first byte after the boot section aka 0x200 if it is 0xFF and remember that. Afterall, either there is the vector table with jmps (not ff), or somone is doing vodoo with sbic/sbis (results in ff xx op code) on the first isr vector, and I don't think we need to handle this kind of vodoo?
In order to be backwards compatible, I still have to provide for a way to erase the flash, when no chip erase happend.
However, in the flash_write assembly, even though I branch over the flash erase section, I cannot get away from the 18.2sec needed to program the 112k optiboot example??? 
I mean, considering the erase cmd takes 10ms, with 256 pages this should give us a difference of at least 2 secs? But nope ain't seeing that.
So it seems like I'm not able to increase programming speed. All I can suggest is to ramp serial speed to 250k (should give us a nice BAUD value of 64 at 4MHz). But again, backwards compatibility would break at that.

**Pull request merged**
