### PR TITLE
ASM magic and gcc hacks on optiboot_dx

### PR DESCRIPTION
**Pull request by MX682X**
Consider this as a request for comments, as this thing is only tested on the avr128da48 with <64k sketches only and build in atmel studio 7 with avr-gcc 7.3.0

List of changes:
UART pointer now lives in Y register, untouchable by gcc (enabled by #define ASM_UART)
-> required some assembly in putch() and getch() as the compiler tried to create a pointer copy in Z
Data copy functions were written in ASM to use a sbiw register. (enabled by #define ASM_UART && #define ASM_COPY)
-> this relies on the knowledge of the clobbered registers in put/get functions
Reduced the amount of arguments in functions and moved some variables to global registers
-> the less bytes the arguments need the easier the optimizations become.
Enabled EEPROM support for Dx

The bootloader now uses 488 bytes

Anyway. this was an 80/20 optimization. 
There are more leverages to reduce size further (I predict about 10-20 words) but it will require even more assembly, and at that point, you can consider rewriting all helper functions to assembly, and if you need even more space then rewrite all parameter passing to that functions in assembly (there is a lot of register moves due to call-clobbering)

EDIT:
requires the optimization flags "-ffixed-r20 -ffixed-r21" to avoid warnings

I really hope that solves the comlaints about not enough space....

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Goddaaaaaamn man! 

I knew there was slack. 

I suspected putting the USART pointer into Y to be one of the ways to improve it. 

But what I suspect, you do, and... it looks like quite rapidly... 

But fitting EEPROM? That's just beyond my wildest dreams.

**Comment by MX682X** [comment]
I should probably add that I haven't verified if EEPROM works, I've just added the define....

**Comment by MX682X** [comment]
Also Also: I'm not entirely sure how addressing/pointer-changes work. I've specified the address as read-write in the asm. If the address is re-sent every time, the code size can be reduced further by making them read-only

**Comment by SpenceKonde** [comment]
Well, it's failing the Chauser112k test.... 
[chaucer112k.hex.txt](https://github.com/SpenceKonde/DxCore/files/13061912/chaucer112k.hex.txt)

**Comment by SpenceKonde** [comment]
No, you don't appear to have missed a WDR... 

But I'm struggling to explain how addresses 0xC000 to 0xC1FF is written correctly, but 0xC200 isn't...  
```
page 0xC000=0xC1FF: Written correctly
:20C0000020746865792C20696E206368616E67696E67206F66207468656972206875650A27
:20C020002A41732066617220617320656974686572206F66207468656D206F74686572200F
:20C040006B6E65772A2E20202020202020202A5768656E2074686579207265636F676E6936
:20C0600073656420656163680A546865726520776173206E6F20676F6F64206461792C20F6
:20C08000616E64206E6F2073616C7574696E672C20202020202020202020202020202020BD
:20C0A00020206F746865722061666172206F66662A0A4275742073747261696768742C20D8
:20C0C000776974686F75746520776F726465732072656865617273696E672C0A4576657223
:20C0E00065616368206F66207468656D20686F6C7020746F2061726D20746865206F7468EA
:20C1000065722C0A417320667269656E646C792C206173206865207765726520686973207D
:20C120006F77656E2062726F746865722E0A416E6420616674657220746861742C207769B6
:20C140007468207368617270652073706561726573207374726F6E670A5468657920666FF7
:20C16000696E65642A2065616368206174206F7468657220776F6E646572206C6F6E672E60
:20C1800020202020202020202020202020202020202020202020202020202A7468727573FF
:20C1A000740A54686F75206D69676874657374207765656E652A2C2074686174207468691C
:20C1C000732050616C616D6F6E202020202020202020202020202020202020202020202024
:20C1E000202020202A7468696E6B0A496E206669676874696E6720776572652061732061FE
```
page 0xC200-0xC2FF: Not written.
```
:20C20000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3E
:20C22000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1E
:20C24000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
:20C26000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDE
:20C28000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBE
:20C2A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9E
:20C2C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7E
:20C2E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5E
:20C30000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3D
:20C32000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1D
:20C34000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD
:20C36000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDD
:20C38000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBD
:20C3A000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9D
:20C3C000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7D
:20C3E000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D
```
Errors (error behavior is: 
```
(base) C:\Data\TOOLS\avrdude\avrdude_7.2-arduino.1_Windows_32bit\avrdude_Windows_32bit\bin>avrdude -c arduino -D -p avr128DB64 -P COM21 -b 115200 -U flash:w:chaucer112k.hex:i
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e970b (probably avr128db64)

avrdude: processing -U flash:w:chaucer112k.hex:i
avrdude: reading input file chaucer112k.hex for flash
         with 111138 bytes in 1 section within [0x200, 0x1b421]
         using 218 pages and 478 pad bytes
avrdude: writing 111138 bytes flash ...
Writing | ######################                             | 44% 6.99 s ^C
```
Have to ctrl+c out of it at that point - the bootloader is doing the triple blink as it has reset, it ain't gonna finish at that point, and if I don't kill it like that. it spams "failed" when it times out and blows away all the command window history. 

Same behavior in avrdude 6.3 and 7.2

Read works on both
```
(base) C:\Data\TOOLS\avrdude\avrdude_7.2-arduino.1_Windows_32bit\avrdude_Windows_32bit\bin>avrdude -c arduino -D -p avr128DB64 -P COM21 -b 115200 -U flash:r:readdata.hex:i
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e970b (probably avr128db64)

avrdude: processing -U flash:r:readdata.hex:i
avrdude: reading flash memory ...
Reading | ################################################## | 100% 12.09 s
avrdude: writing output file readdata.hex

avrdude done.  Thank you.
```


With ascii decodings omitted, maximum verbosity, no smoking gun.... 
```
avrdude: recv:[14]
avrdude: recv:[10]
avrdude: send:[55][00][be][20]
avrdude: recv:[14]
avrdude: recv:[10]
avrdude: send:[64][02][00][46]
[74][2c][0a][54][68][69][73][20][41][72][63][69][74][65][20][61][6e][64][20][74][68][69][73][20][50][61][6c][61][6d][6f][6e][20]
[62][65][20][6d][65][74][2e][0a][54][68][65][6e][20][63][68][61][6e][67][65][20][67][61][6e][20][74][68][65][20][63][6f][6c][6f]
[75][72][20][6f][66][20][74][68][65][69][72][20][66][61][63][65][3b][0a][52][69][67][68][74][20][61][73][20][74][68][65][20][68]
[75][6e][74][65][72][20][69][6e][20][74][68][65][20][72][65][67][6e][65][2a][20][6f][66][20][54][68][72][61][63][65][20][20][20]
[20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][2a][6b][69][6e][67][64][6f][6d][0a][54][68][61][74][20]
[73][74][61][6e][64][65][74][68][20][61][74][20][61][20][67][61][70][70][65][20][77][69][74][68][20][61][20][73][70][65][61][72]
[0a][57][68][65][6e][20][68][75][6e][74][65][64][20][69][73][20][74][68][65][20][6c][69][6f][6e][20][6f][72][20][74][68][65][20]
[62][65][61][72][2c][0a][41][6e][64][20][68][65][61][72][65][74][68][20][68][69][6d][20][63][6f][6d][65][20][72][75][73][68][69]
[6e][67][20][69][6e][20][74][68][65][20][67][72][65][76][65][73][2a][2c][20][20][20][20][20][20][20][20][20][20][20][20][20][20]
[20][20][20][20][20][20][20][2a][67][72][6f][76][65][73][0a][41][6e][64][20][62][72][65][61][6b][69][6e][67][20][62][6f][74][68]
[20][74][68][65][20][62][6f][75][67][68][65][73][20][61][6e][64][20][74][68][65][20][6c][65][61][76][65][73][2c][0a][54][68][69]
[6e][6b][65][74][68][2c][20][22][48][65][72][65][20][63][6f][6d][65][73][20][6d][79][20][6d][6f][72][74][61][6c][20][65][6e][65]
[6d][79][2c][0a][57][69][74][68][6f][75][74][65][20][66][61][69][6c][2c][20][68][65][20][6d][75][73][74][20][62][65][20][64][65]
[61][64][20][6f][72][20][49][3b][0a][46][6f][72][20][65][69][74][68][65][72][20][49][20][6d][75][73][74][20][73][6c][61][79][20]
[68][69][6d][20][61][74][20][74][68][65][20][67][61][70][3b][0a][4f][72][20][68][65][20][6d][75][73][74][20][73][6c][61][79][20]
[6d][65][2c][20][69][66][20][74][68][61][74][20][6d][65][20][6d][69][73][68][61][70][3a][22][0a][53][6f][20][66][61][72][65][64]
[20]
avrdude: recv:[14]
avrdude: recv:[10]
avrdude: send:[55][00][c0][20]
avrdude: recv:[14]
avrdude: recv:[10]
avrdude: send:[64][02][00][46]
[20][74][68][65][79][2c][20][69][6e][20][63][68][61][6e][67][69][6e][67][20][6f][66][20][74][68][65][69][72][20][68][75][65][0a]
[2a][41][73][20][66][61][72][20][61][73][20][65][69][74][68][65][72][20][6f][66][20][74][68][65][6d][20][6f][74][68][65][72][20]
[6b][6e][65][77][2a][2e][20][20][20][20][20][20][20][20][2a][57][68][65][6e][20][74][68][65][79][20][72][65][63][6f][67][6e][69]
[73][65][64][20][65][61][63][68][0a][54][68][65][72][65][20][77][61][73][20][6e][6f][20][67][6f][6f][64][20][64][61][79][2c][20]
[61][6e][64][20][6e][6f][20][73][61][6c][75][74][69][6e][67][2c][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20]
[20][20][6f][74][68][65][72][20][61][66][61][72][20][6f][66][66][2a][0a][42][75][74][20][73][74][72][61][69][67][68][74][2c][20]
[77][69][74][68][6f][75][74][65][20][77][6f][72][64][65][73][20][72][65][68][65][61][72][73][69][6e][67][2c][0a][45][76][65][72]
[65][61][63][68][20][6f][66][20][74][68][65][6d][20][68][6f][6c][70][20][74][6f][20][61][72][6d][20][74][68][65][20][6f][74][68]
[65][72][2c][0a][41][73][20][66][72][69][65][6e][64][6c][79][2c][20][61][73][20][68][65][20][77][65][72][65][20][68][69][73][20]
[6f][77][65][6e][20][62][72][6f][74][68][65][72][2e][0a][41][6e][64][20][61][66][74][65][72][20][74][68][61][74][2c][20][77][69]
[74][68][20][73][68][61][72][70][65][20][73][70][65][61][72][65][73][20][73][74][72][6f][6e][67][0a][54][68][65][79][20][66][6f]
[69][6e][65][64][2a][20][65][61][63][68][20][61][74][20][6f][74][68][65][72][20][77][6f][6e][64][65][72][20][6c][6f][6e][67][2e]
[20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][2a][74][68][72][75][73]
[74][0a][54][68][6f][75][20][6d][69][67][68][74][65][73][74][20][77][65][65][6e][65][2a][2c][20][74][68][61][74][20][74][68][69]
[73][20][50][61][6c][61][6d][6f][6e][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20]
[20][20][20][20][2a][74][68][69][6e][6b][0a][49][6e][20][66][69][67][68][74][69][6e][67][20][77][65][72][65][20][61][73][20][61]
[20]
avrdude: recv:[14]
avrdude: recv:[10]
               set address 0xC200
avrdude: send:[55][00][c2][20]
avrdude: recv:[14]
avrdude: recv:[10]
               Write 0x200 bytes 
avrdude: send:[64][02][00][46]
[20][77][6f][6f][64][2a][20][6c][69][6f][6e][2c][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][20]
[20][20][20][20][20][20][20][20][20][20][20][20][20][20][20][2a][6d][61][64][0a][41][6e][64][20][61][73][20][61][20][63][72][75]
[65][6c][20][74][69][67][65][72][20][77][61][73][20][41][72][63][69][74][65][3a][0a][41][73][20][77][69][6c][64][65][20][62][6f]
[61][72][73][20][67][61][6e][20][74][68][65][79][20][74][6f][67][65][74][68][65][72][20][73][6d][69][74][65][2c][0a][54][68][61]
[74][20][66][72][6f][74][68][20][61][73][20][77][68][69][74][65][20][61][73][20][66][6f][61][6d][2c][20][2a][66][6f][72][20][69]
[72][65][20][77][6f][6f][64][2a][2e][20][20][20][20][20][20][20][20][20][20][20][20][2a][6d][61][64][20][77][69][74][68][20][61]
[6e][67][65][72][2a][0a][55][70][20][74][6f][20][74][68][65][20][61][6e][63][6c][65][20][66][6f][75][67][68][74][20][74][68][65]
[79][20][69][6e][20][74][68][65][69][72][20][62][6c][6f][6f][64][2e][0a][41][6e][64][20][69][6e][20][74][68][69][73][20][77][69]
[73][65][20][49][20][6c][65][74][20][74][68][65][6d][20][66][69][67][68][74][69][6e][67][20][64][77][65][6c][6c][2c][0a][41][6e]
[64][20][66][6f][72][74][68][20][49][20][77][69][6c][6c][20][6f][66][20][54][68][65][73][65][75][73][20][79][6f][75][20][74][65]
[6c][6c][2e][0a][0a][54][68][65][20][44][65][73][74][69][6e][79][2c][20][6d][69][6e][69][73][74][65][72][20][67][65][6e][65][72]
[61][6c][2c][0a][54][68][61][74][20][65][78][65][63][75][74][65][74][68][20][69][6e][20][74][68][65][20][77][6f][72][6c][64][20]
[6f][27][65][72][20][61][6c][6c][0a][54][68][65][20][70][75][72][76][65][79][61][6e][63][65][2a][2c][20][74][68][61][74][20][47]
[6f][64][20][68][61][74][68][20][73][65][65][6e][20][62][65][66][6f][72][6e][3b][20][20][20][20][20][20][20][20][20][20][20][20]
[20][20][2a][66][6f][72][65][6f][72][64][69][6e][61][74][69][6f][6e][0a][53][6f][20][73][74][72][6f][6e][67][20][69][74][20][69]
[73][2c][20][74][68][61][74][20][74][68][6f][75][67][68][20][74][68][65][20][77][6f][72][6c][64][20][68][61][64][20][73][77][6f]
[20]
```
And here it hangs - looks like it's not getting the 0x14 0x10, likely because optiboot isn't sending them. The question is why...

**Comment by MX682X** [comment]
Oh I know what the problem is, had to deal with this before hand. This happens when verifySpace isn't getting a Space (I think I still have a software breakpoint there, so if you hook up a debugger you can check the last USART byte). This will lead to a shorten wdr with infinite loop.
A Space is missed if the amount of getch is wrong. In other words, one of the lengths is parsed wrong.

Am 22. Oktober 2023 02:39:56 MESZ schrieb "Spence Konde (aka Dr. Azzy)" ***@***.***>:

**Comment by MX682X** [comment]
Figured it out: Stack corruption.

**Comment by SpenceKonde** [comment]
my gut told me it was something like that. We're using the stack for.... just the calls right?

Ready for corrected code whenever. I'm, hoping to get all the bootloader and upload stuff sorted out with AVRdude 7.2 soon, or determine that 7.2 is no good.

**Comment by MX682X** [comment]
Yes, calls only. Figured it out when I ended up at PC 0x7FFFFFFF without a reset cause. I had the RAMSTART global Variable wrongfully set as read-write at some point....

I had some trouble with some version of avrdude 7.2 and Curiosity nano. it didn't send anything on UART... I didn't get to investigate the problem further though, as I just went back to the one shipped by arduino.

**Pull request merged**
