### PR TITLE
removed bad TWI definitions

### PR DESCRIPTION
**Pull request by MX682X**
the ALT 1 position was changing the dual mode slave pins, but theese parts don't have this pins, so the io.h file doesn't have the bitmap defined which didn't let the code compile with the new Wire library

### CODE REVIEW

**Comment by MX682X** [comment]
most of those failed checks are not related to the changes I've made.

**Comment by SpenceKonde** [comment]
Yeah, I 100% agrree and expected that, You had the misfortune to open a PR between my checking in changes and fixing the linting errors. That's why I didn't say anything about them :-P

**Comment by SpenceKonde** [comment]
I believe it currently (the form in master, not your version) works as documented. There are two swap options, 0 and 1, and the library is only concerned with the master/slave mode pins, not the other ones, These correspond to default and alt2 positions, because as far as the previous version of the library was concerned, alt1 and default were the same, since it had no support for dual mode. In hindsight, that wasn't the best decision (I didn't make it - but I would have done the exact same thing if I were the one making the decision at the time - so I'm not casting shade on that). 

The implementation is from MegaCoreX (the swapping mechanism was stolen from there at MCUdude's request). To my absolute astonishment, MegaCoreX doesn't get requests for dual mode or simultaneous master and slave (It's one of the most loudly requested features on my cores - my presumed use case for the dual mode parts is that you have a Dx acting as shepherd for a whole bunch of I2C devices, while something bigger, computationally faster, and lower voltage doing something with the combined data, which if gets from the the Dx over the slave mode pins on PC2/3 which are running at the big device's I/O voltage, or the whole chip is running at that voltage except for PC ). So from that perspective, there's no reason it would ever be implemented ("nobody even wants it"), and from there, you look at the list of pin options, disregard the slave-only pins and see two possibilities, default and alt2 because alt1 is a duplicate. It'd be confusing to get the same results when you pass two different swap options right? and with only 2 option and no expectation of ever supporting the middle one, why would you include the middle option?  So then you reach the result: . "Okay so either it's on the default pins or the alt2 ones, so user shall pass 0 or 1 to TWI.swap()." 

Since then the only consideration it's gotten was that I added tinyAVR support via #ifdefs and then did much the same in order to get Dx-series working. 

I don't think I ever even noticed that the mappings change from 
PA2/3&PC2/3, PA2/3&**PF2/3**, PC2/3&**PF2/3**
to
PA2/3&PC2/3, PA2/3&**PC6/7** PC2/3&**PC6/7**
and
_PF/3_&PB2/3, _PF/3_&PB6/7, PB2/3&PB6/7

But, hmm. We're going to have a problem here. 
If change the numbering, we break existing code (if there is any - unfortunately I think there probably is by now. It's been out like a year). 
If not, no matter how we do it the new functionality is counterintuitive, and we want to move in the direction of being more intuitive, not less. 

Right now I'm working get DxCore 1.3.7 out having missed my target of last night, so I can pull in the TWI and Serial changes and start testing them out

The version that gets them will likely be numbered 1.4.0 and be "DD-ready", since the fact that Serial pinswap didn't scale to serial ports with 7 mapping options was the last blocking issue (well, that and the pins_arduino files. but those will go in soon.

**Comment by SpenceKonde** [comment]
Oh fuck, it's busted completely currently lol and never worked the qway I was remembering /facepalm

**Comment by SpenceKonde** [comment]
Changes made manually

**Pull request closed without merging**
