### PR TITLE
Opamp library

### PR DESCRIPTION
**Pull request by MCUdude**
Note that even though the library compiles, I have not tested it on actual hardware, because I don't own any.
@SpenceKonde could you test this and confirm if it works or not?

### CODE REVIEW

**Comment by MCUdude** [comment]
I can't be blamed for all this Ci errors. I got **SIX** emails telling me that the CI failed. Is that really necessary?

**Comment by SpenceKonde** [comment]
Sorry, the repo has a ton of CI failures - I just put CI stuff in a couple of days ago. (run the tests locally before I put them in master? Ain't nobody got time for that!) And now it turns out that, in addition to the CI issues, there are several nasty bugs  reported plus several that I found following up on those....So this repo is suddenly the top priority - I do so wish I'd known over the weekend so I could have fixed it then instead of farting around and gaming out absurd uses of Logic and Event!

I do not know how to control the email messages; I *want* to get an email for every failed CI pass, but I don't want to inflict it on people submitting PR's. Of course, once master is passing CI, it won't so much be a problem.

**Comment by per1234** [comment]
There's no way to configure notification settings for other people.

Each user needs to configure their own notifications individually in their GitHub settings. But I recommend leaving nofications for GitHub Actions enabled because it can be very important to know when the CI failed on a pull request you submitted (though not so much in this case). For me, one of the huge benefits of setting this sort of thing up is that the automated system does the initial triage on PRs, and you can just leave it to the contributors and the CI to work things out, saving your review time for the things a computer can't easily detect after all the basic issues have been resolved. But if the contributor doesn't get that feedback that something is wrong with the PR then they won't resolve the issue.

What you can do is disable broken workflows:

1. Open the ["Actions" tab](https://github.com/SpenceKonde/DxCore/actions)
2. Select the workflow from the menu on the left side of the window.
3. Click the ". . ." button near the top right side of the window.
4. Click "Disable workflow".

But make sure to enable the workflow via a similar process once you have fixed it.

**Comment by MCUdude** [comment]
@SpenceKonde so how about the PR itself?

**Comment by SpenceKonde** [comment]
Havent looked at it, my development copy of dxcore is not in a usable state
- I'm halfway through fixing a bunch of initialization bugs I found while
investigating reports that analogRead was hanging the Dx parts in 1.3.0,
(trivial fix, but realized timekeeping and timer init was wrong too) but
until that is done and the boards.txt issue is fixed, the critical bugs
have to take priority.

I admit that I did a lousy job of prioritizing over the weekend, tried to
finish some low priority docs before working on other things, but wound up
barely finishing them!

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by MCUdude** [comment]
Really? Did everything work like it should? I don't own any DB hardware, so I hope you've tested it.

**Comment by SpenceKonde** [comment]
Oh of course I didn't test it yet! Why would I test *before* I merged something?  That's crazy talk! I was slamming a ton of changes through making all the CI checks (other than compile-tests, since I don't have those except for megaTinyCore, and for a short time more, ATTinyCore).I was getting nervous that I was going to end up with master out of sync and it would be a whole big thing to get working again, so I just merged it in. 

 Planning to test before I release 1.3.1 :-P but really - so what if I didn't? Someone would try it, it wouldn't work, and then they'd make an issue or whine on the forums and it could be fixed *shrug* As long as it's a new feature, it doesn't truly matter if it works or not. Once a previous version is released and works, there's a much higher expectation of functionality.... 

I mean, FFS, I've released ATTinyCore with init() busted on the second most popular part such that it didn't start millis running (delay happened to misbehave spectacularly too - the delay would go by almost instantly!!

**Pull request merged**
