### PR TITLE
Wire rework

### PR DESCRIPTION
**Pull request by MX682X**
Alright, so kinda big changes:
- pulled twi.c into Wire.cpp, the seperation wasn't needed
- Master and Slave don't have seperate tx and rx buffers anymore, as the mode of operation is defined by the read/write bit so there is no interfereing between tx and rx between start and stop (saves like 50% of ram)
- reworked the slave isr routine to save some flash (a fresh look helps a lot)
- added masterTransmit/masterReceive functions that write directly to a user buffer (useful if you are tired of the Arduino API)
  - the Arduino API are basically just wrappers for this functions now
- replaced the define BUFFER_LENGTH with TWI_BUFFER_LENGTH (maybe WIRE_BUFFER_LENGTH would be better?) while maintaining backwards capability

### CODE REVIEW

**Comment by MX682X** [comment]
gonna finish updating the docs a bit later

**Comment by mikrocoder** [comment]
Hi,
Very nice. 
TWI_BUFFER_LENGTH is the better name.
WIRE_BUFFER_LENGTH could be confused with OneWire.
My opinion.

**Comment by MCUdude** [comment]
I've been using `TWI_BUFFER_SIZE` for the last four years with [MegaCoreX](https://github.com/MCUdude/MegaCoreX). It could be a good idea to keep the names similar.

**Comment by SpenceKonde** [comment]
Sorry for the awful delay here, have been moving between shitty temporary locations cause my  roommates fucked me over and didn;t tell me they weren't re-signing lease.... half an hour before they told the land lord.

**Comment by MX682X** [comment]
Yeah, that soubds awful. I hope you were able to find something stable.

However it would be good to read your thoughts aswell about the Naming of the define. We have two options....

**Pull request merged**
