### PR TITLE
Spellcheck

### PR DESCRIPTION
**Pull request by nomakewan**
Performed cursory spellcheck pass. This is in no way comprehensive and there are still a huge amount of spelling errors, incorrect grammar, and highly unnecessary text present. That said, this should at least correct a few rather important ones and get rid of that pesky Actions failure on commits.

Line 421 of Ref_Timers.md trails off without finishing the sentence. Please advise.

Please check line 446 or Ref_Timers.md for accuracy (removed bunch of unnecessary text but may have gotten the output wrong as a result).

Line 553 of wiring.c also trails off without finishing its thought. Please advise.

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Argh, we were both working on the same issue at the same time...

**Comment by nomakewan** [comment]
Yeah, just noticed that. I did fix more than just what was in the Actions, though, including a typo in boards.txt for the DU-series. I don't mind at all, I'll wait for the checks to complete then see about resolving the conflicts.

**Comment by nomakewan** [comment]
Okay, updated Ref_Timers.md to match your new changes and fix an additional new typo. Looks like the failing checks now aren't actually failing as a result of my changes, but rather because the Github Actions bot is being rate-limited while performing so many compile operations. The only thing I changed in an example was a typo in a header comment, after all, so there should be no difference compile-wise between this PR and the base repo.

**Comment by nomakewan** [comment]
Spoke too soon; looks like now the compile examples are also failing due to not being able to get python 3.8 as a result of a GPG signature failure. Again, looks like a problem with Github Actions, not with the PR.

**Comment by SpenceKonde** [comment]
All these tests that can break based on factors completely unrelated to the code being tested are a right pain in the arse aren't they? 

Believe it or not, EVEN THE SPELL CHECK IS LIKE THAT. Codespell uses it's own dictionary of words (ie, it uses a blacklist instead of a whitelist, because they want to only catch things that are actually misspelled words, as opposed to non-words used as variable names)

**Pull request merged**
