### PR TITLE
Adapt for use with PlatformIO

### PR DESCRIPTION
**Pull request by brunob45**
This PR enables the use of this Arduino framework in [PlatformIO](https://platformio.org/), a tool to program, compile and upload embedded in VS Code/Atom.

The PlatformIO packages need to be organized [a specific way](https://github.com/platformio/platform-teensy), so I moved the files in the correct configuration.
Also, I added in the root directory a `package.json` file describing the framework.

I did an example project ([blink](https://github.com/brunob45/dev-AVR-Dx)) to show how these changes can be used.

Ultimately, PlatformIO should embed a link to your framework for a more streamline installation (I'll make a PR to merge [this branch](https://github.com/brunob45/platform-atmelmegaavr)).

P.S. good work, I just tried version 1.3 on a AVR128DA48 Curiosity Nano board, everything is working as exepected! I'm excited to see what comes next

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Hm - it looks like this change mirrors the format used by board manager (and which is incompatible with manual installation) - I do already release packages without the megaavr (or avr) folder layer to support board manager installation. Am I understanding this correctly? 
@MCUdude's packages are formatted the same way as mine within the repo (I just clone his repos into hardware, same as mine), and as I understand, those are available on platform IO; I'd love to have platform IO support, but we need to do it however those are done, so manual installation can be done by just syncing repo to hardware.

**Comment by MCUdude** [comment]
@SpenceKonde you don't have to do _anything_ to this repo in order to get official PlatformIO support. All we need is to get [platform-megaavr#18](https://github.com/platformio/platform-atmelmegaavr/pull/18) merged. The PlatformIO developers do the rest, and as far as I've understood is how they prefer it. I've asked several times if there is anything I can do to make their job easier, but I haven't got a clear answer. After platform-megaavr#18 gets merged, I'll start working on supporting dynamic fuse calculation for the DA and DB parts. The script for this is [here](https://github.com/platformio/platform-atmelmegaavr/blob/develop/builder/fuses.py) by the way.

What you can do after my PR (hopefully) gets merged is to provide some PlatformIO/DxCore specific documentation, similar to what I've done to MegaCoreX [here](https://github.com/MCUdude/MegaCoreX/blob/master/PlatformIO.md).

as an FYI, megaTinyCore is already supported by PlatformIO (because of me 😉), but they haven't released the megaavr package with them yet. It includes support for all tiny0/1's and dynamic fuse calculation, pretty much identical to what's documented in the MegaCoreX PlatformIO.md file.

**Comment by brunob45** [comment]
I'm new at this, but I made it work, and wanted to share. Considering what @MCUdude said, I would not merge this PR.

**Comment by SpenceKonde** [comment]
I appreciate the attitude :-) 

Now, if only we could get the platformIO people to do a bit of updating - it's frustrating to see that work has been done, but they seem to have lost interest in megaavr?

**Comment by MCUdude** [comment]
> Now, if only we could get the platformIO people to do a bit of updating - it's frustrating to see that work has been done, but they seem to have lost interest in megaavr?

My experience is that even though they are very slow to respond sometimes (due to lots on their plate I think) they never forget it and usually reach out a few weeks or perhaps months later. When they finally do, they're usually "available" until the issue/PR is solved.

**Comment by brunob45** [comment]
I don't know the size of their team, but it sure is a lot of work to support every platform, toolchain, framework and tool they provide, by themselves... 
Speaking of toolchain, their amtelavr toolchain only have the spec files of AVR128DA, and none of the others. It may be another reason they don't support DxCore yet...

**Comment by SpenceKonde** [comment]
Sigh, do they rely on the same arduino7 build as everyone else?

I finally released a working toolchain package of my own for DxCore to pick up support for the rest of the DA series and the DB-series parts.

**Pull request closed without merging**
